# Generated by Django 3.0.5 on 2020-07-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maxSize',
            field=models.IntegerField(default=26),
        ),
        migrations.AddField(
            model_name='product',
            name='minSize',
            field=models.IntegerField(default=21),
        ),
    ]
