# Generated by Django 3.0.5 on 2020-07-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200730_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('Men', 'Men'), ('Woman', 'Woman')], max_length=20),
        ),
    ]
